Update README.md
openclarity/.github pull request #27
Opened 2023-10-30 14:34 UTC by fekete-robert

Adds openclarity logo and updates component names

2023-10-30 19:48 UTC, lelia commented
@Tehsmash / @lgecse could either of you confirm that these project renames are in-line with broader plans to unify OpenClarity? Are we also changing the official casing from `OpenClarity` to `Openclarity` ?

(ref: https://github.com/openclarity/vmclarity/pull/869#pullrequestreview-1704460130)

2023-11-06 14:24 UTC, fekete-robert commented on profile/README.md
> +## [API Security](https://github.com/openclarity/apiclarity)
```suggestion
## API Security
```

2023-11-06 14:25 UTC, fekete-robert commented on profile/README.md
> +API Security is an open source tool for APIs that helps you visualize and identify potential risks around API usage in your cloud native environments. It helps build the OpenAPI specifications for al
```suggestion
[APIClarity](https://github.com/openclarity/apiclarity) is an open source tool for APIs that helps you visualize and identify potential risks around API usage in your cloud native environments. It helps build the OpenAPI specifications for all APIs in your environment, then helps track drift, shadow or zombie usage for those APIs. You can then use this information to build your application security posture.
```

2023-11-06 18:31 UTC, lgecse approved these changes

2023-11-07 15:20 UTC, fekete-robert commented on profile/README.md
> +Openclarity is an open-source platform to enhance security and observability of cloud-native applications and infrastructure.
```suggestion
Openclarity is an open source platform to enhance security and observability of cloud-native applications and infrastructure.
```

2023-11-07 15:21 UTC, lgecse requested changes

2023-11-07 15:26 UTC, lgecse approved these changes

2023-11-07 19:18 UTC, lgecse commented
> @Tehsmash / @lgecse could either of you confirm that these project renames are in-line with broader plans to unify OpenClarity? Are we also changing the official casing from `OpenClarity` to `Openclarity` ?
> 
> (ref: [openclarity/vmclarity#869 (review)](https://github.com/openclarity/vmclarity/pull/869#pullrequestreview-1704460130))

@lelia Thanks for bringing this up, I confirm we are **not** changing `OpenClarity` to `Openclarity`. This was only a misunderstanding.

2023-11-07 19:18 UTC, lgecse approved these changes

2023-11-07 19:21 UTC, lgecse requested changes
Please keep the OpenClarity naming, and make the whole file consistent.

2023-11-07 19:21 UTC, lgecse commented on profile/README.md
> +# [Openclarity](https://openclarity.io)
Please keep the OpenClarity naming, and make the whole file consistent.

2023-11-07 19:21 UTC, lgecse commented on profile/README.md
> +Openclarity delivers:
Please keep the OpenClarity naming, and make the whole file consistent.

2023-11-07 19:21 UTC, lgecse commented on profile/README.md
> +Openclarity is a suite of open source tools for cloud native security and observability — VM Security, Kubernetes Security, and API Security. Read more about each project below.
Please keep the OpenClarity naming, and make the whole file consistent.

2023-11-08 09:15 UTC, fekete-robert commented on profile/README.md
> +Openclarity delivers:
```suggestion
[OpenClarity](https://openclarity.io) is an open source platform to enhance security and observability of cloud-native applications and infrastructure.
OpenClarity delivers:
```

2023-11-08 09:15 UTC, fekete-robert commented on profile/README.md
> +Openclarity is a suite of open source tools for cloud native security and observability — VM Security, Kubernetes Security, and API Security. Read more about each project below.
```suggestion
OpenClarity is a suite of open source tools for cloud native security and observability — VM Security, Kubernetes Security, and API Security. Read more about each project below.
```

2023-11-08 09:16 UTC, fekete-robert commented on profile/README.md
> +# [Openclarity](https://openclarity.io)
```suggestion
# [OpenClarity](https://openclarity.io)
```

2023-11-08 09:16 UTC, fekete-robert commented on profile/README.md
> +  <img alt="Openclarity logo" src="https://docs.openclarity.io/img/color-logo/logo.svg" width="50%">
```suggestion
  <img alt="OpenClarity logo" src="https://docs.openclarity.io/img/color-logo/logo.svg" width="50%">
```

2023-11-08 10:12 UTC, lgecse approved these changes

2023-11-18 15:59 UTC, justaugustus requested changes
Adding some minor copyedits.
I'll apply the suggestions and merge this. Feel free to take any outstanding reviews as follow-up PRs.

2023-11-18 15:59 UTC, justaugustus commented on profile/README.md
> +<picture>
```suggestion

<picture>
```

2023-11-18 15:59 UTC, justaugustus commented on profile/README.md
> +[OpenClarity](https://openclarity.io) is an open source platform to enhance security and observability of cloud-native applications and infrastructure.
```suggestion
[OpenClarity](https://openclarity.io) is a suite of open source projects built to enhance the security and observability of cloud native applications and infrastructure.
```

***Not a platform

2023-11-18 15:59 UTC, justaugustus commented on profile/README.md
> +OpenClarity delivers:
```suggestion

OpenClarity delivers:
```

2023-11-18 15:59 UTC, justaugustus commented on profile/README.md
> +- Agent-less detection and managements of vulnerabilities, exploits, malware and misconfigurations for VMs and Container Images
```suggestion
- Agentless detection and managements of vulnerabilities, exploits, malware and misconfigurations for virtual machines and container images
```

2023-11-18 15:59 UTC, justaugustus commented on profile/README.md
> +OpenClarity is a suite of open source tools for cloud native security and observability — VM Security, Kubernetes Security, and API Security. Read more about each project below.
```suggestion
```

This repeats effectively repeats the opening line of the readme.

2023-11-18 15:59 UTC, justaugustus commented on profile/README.md
> +[APIClarity](https://github.com/openclarity/apiclarity) is an open source tool for APIs that helps you visualize and identify potential risks around API usage in your cloud native environments. It he
```suggestion
[APIClarity](https://github.com/openclarity/apiclarity) is a tool that helps you visualize and identify potential risks around API usage in your cloud native environments. It helps build the OpenAPI specifications for all APIs in your environment, then helps track drift, shadow or zombie usage for those APIs. You can then use this information to build your application security posture.
```

2023-11-18 15:59 UTC, justaugustus commented on profile/README.md
> +[VMClarity](https://github.com/openclarity/vmclarity) is an open source tool for agentless detection and management of Virtual Machine Software Bill Of Materials (SBOM) and security threats such as v
```suggestion
[VMClarity](https://github.com/openclarity/vmclarity) is a tool for agentless detection and management of virtual machine Software Bill Of Materials (SBOM) and security threats such as vulnerabilities, exploits, malware, rootkits, misconfigurations, and leaked secrets.
```

2023-11-18 16:01 UTC, justaugustus approved these changes

2023-11-18 16:02 UTC, merged