[WIP] GitHub Organization Config (v1)
openclarity/.github pull request #9
Opened 2023-04-18 22:49 UTC by lelia

# [WIP] GitHub Organization Config (v1)

2023-04-24 18:39 UTC, justaugustus requested changes
Great start, @lelia!

As next steps, I'd suggest two things:
1. I flagged a few file changes that I think can be safely pulled into a separate PR and merged.
2. Check out peribolos' `--dump` commands, so that you can get an [initial seed](https://github.com/uwu-tools/peribolos#initial-seed) of the org configuration, then break that up into the teams structure you've got laid out here

Okay, wait, two nits as well:
1. rename `orgs/` to `org/` or `config/`, etc., as this directory will only cover configuration for the `openclarity` org
2. let's opt to use probot settings GitHub App for the per repo configurations.

2023-04-24 18:39 UTC, justaugustus commented on .github/CODEOWNERS
Let's pull these changes out into a separate PR (can combine in a PR with the other file changes I flagged).

2023-04-24 18:39 UTC, justaugustus commented on .github/dependabot.yml
Let's pull these changes out into a separate PR (can combine in a PR with the other file changes I flagged).

2023-04-24 18:39 UTC, justaugustus commented on .github/stale.yml
Let's pull these changes out into a separate PR (can combine in a PR with the other file changes I flagged).

2023-04-24 18:39 UTC, justaugustus commented on .yamllint.yml
Let's pull these changes out into a separate PR (can combine in a PR with the other file changes I flagged).

2023-04-24 18:39 UTC, justaugustus commented on .github/workflows/test-sync.yml
> +      #     fix-team-repos: true
```suggestion
```

Let's opt to use Probot Settings for the per repo configurations.

2023-04-25 18:28 UTC, lelia commented on .github/CODEOWNERS
See https://github.com/openclarity/.github/pull/12

2023-04-25 19:32 UTC, justaugustus reviewed
https://github.com/openclarity/.github/pull/12 has merged, so those changes are safe to rebase out :)

2023-07-06 10:01 UTC, justaugustus requested changes
@lelia -- Oh, one more thing!
Please squash the existing commits on the next push :)

2023-07-25 22:47 UTC, lelia commented on .github/workflows/dry-run.yml
Agree that using a `dev` branch -> `main` sync workflow is probably the easiest way to work around this limitation and avoid the known issues with using `pull_request_target:` triggers. I'm going to test that branching model out in `/cisco-ospo` and port the workflow logic here once it's confirmed working.

Also going to file a ticket to investigate some solutions offered [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) and [here](https://blog.gitguardian.com/github-actions-security-cheat-sheet/) as a longer-term fix ✅

2023-08-02 00:43 UTC, lelia commented on .github/workflows/dry-run.yml
Proof-of-concept example demonstrating the PR -> merge to `develop` -> dry run (`confirm: false`) workflow: https://github.com/cisco-ospo/.github/actions/runs/5733062747

A successful run of this job results in a prod run (`confirm: true`) being triggered after the code is synced from `develop` to `main`: https://github.com/cisco-ospo/.github/actions/runs/5733068217

2023-08-02 00:45 UTC, lelia commented on org/README.md
> +Peribolos presently runs on a scheduled (hourly) and event-driven (merges to `main`) basis. These organization sync jobs are configured in [sync-org.yml](../.github/workflows/sync-org.yml). When new
( Going to leave `README.md` untouched until we confirm the fork PR -> dry run on `develop` -> sync code to `main` -> prod run on `main` workflow is what we want to go with )

2023-08-02 01:11 UTC, lelia commented on org/openclarity/chainclarity/teams.yaml
To that end, do we still need the `teams.yaml` file for `functionclarity`, given that's now publicly archived?

2023-08-02 17:56 UTC, lelia commented on org/openclarity/functionclarity/teams.yaml
> +    privacy: closed
Restore chainclarity (for now)

2023-08-04 23:14 UTC, lelia commented on .github/workflows/dry-run.yml
> +      confirm: false
Might make more sense to run these jobs in parallel

2023-08-04 23:15 UTC, lelia commented on .github/workflows/dry-run.yml
> +          force: false
Might not need this if we can run validation workflows (which could include linting and a dry-run) on fork PRs _once they've been approved_

2023-08-04 23:16 UTC, lelia commented on org/README.md
> +        └── org.yaml # Main Peribolos configuration file
Adjust to reflect new reusable workflow structure

2023-08-05 01:19 UTC, lelia commented on org/README.md
> +        └── org.yaml # Main Peribolos configuration file
Done

2023-08-06 09:24 UTC, FrimIdan commented on org/openclarity/chainclarity/teams.yaml
> +---
@lelia I think you confused `chainclarity` (that was a PoC repo that is on hold right now and it's private) with `functionclarity` (that is Public archive)

chainclarity admins are
![image](https://github.com/openclarity/.github/assets/40820488/3e49e52e-87b8-46c2-9ce1-31eab17f1369)
and maintainers are
![image](https://github.com/openclarity/.github/assets/40820488/165c90f2-873d-48ad-a25e-c5d4a6fe1ef1)

2023-08-12 01:29 UTC, lelia commented on org/openclarity/chainclarity/teams.yaml
> +---
Good catch, @FrimIdan ! That was definitely a mis-paste from the `functionclarity` clipboard data 🙂 

I'll push the updated membership affiliations on the next commit.

2023-09-11 20:11 UTC, detiber commented on org/openclarity/org.yaml
> +      - lelia
```suggestion
      - lelia
      - natalisucks
```

2023-09-18 10:05 UTC, openclarity-service approved these changes

2023-09-18 12:35 UTC, justaugustus approved these changes
Great work on this, @lelia!

2023-09-18 12:43 UTC, merged